remote_theme: pages-themes/cayman@v0.2.0
title: Wigle.net UserStyle
description: DarkMode Wigle.Net UserStyle
url: 'https://userstyles.github.typpi.online' # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
